#!/usr/bin/env bash

shopt -s expand_aliases

declare -r service_name='xvfb'

source /etc/profile

alias debug="while read data; do echo -e "${data}" | log debug;   done"
alias info="while read data;  do echo -e "${data}" | log info;    done"
alias warn="while read data;  do echo -e "${data}" | log warning; done"
alias err="while read data;   do echo -e "${data}" | log err;     done"

function log(){
    # ATENCIÓN: NUNCA USAR DIRECTAMENTE, en su lugar utilizar los alias 'debug', 'info', 'warn' y 'err'
    local _severity=${1}; shift;
    logger -p syslog.${_severity} -t ${service_name} -- "${data}"
}

echo "Starting Xvfb - Virtual Framebuffer 'fake' X server" | info
echo -e "$(env)" | debug
exec /usr/bin/Xvfb $DISPLAY -ac -screen 0 1980x1020x24 +extension RANDR 2>&1 | info
