#!/usr/bin/env bash

shopt -s expand_aliases

declare -r service_name='vnc'

source /etc/profile

alias debug="while read data; do echo -e "${data}" | log debug;   done"
alias info="while read data;  do echo -e "${data}" | log info;    done"
alias warn="while read data;  do echo -e "${data}" | log warning; done"
alias err="while read data;   do echo -e "${data}" | log err;     done"

function log(){
    # ATENCIÓN: NUNCA USAR DIRECTAMENTE, en su lugar utilizar los alias 'debug', 'info', 'warn' y 'err'
    local _severity=${1}; shift;
    logger -p syslog.${_severity} -t ${service_name} -- "${data}"
}

echo "Starting VNC server to allow remote access to an existing X session" | info
mkdir /.vnc && x11vnc -storepasswd "${VNC_PASSWORD}" /.vnc/passwd 2>&1 | info
exec /usr/bin/x11vnc -forever -geometry 1980x1020 -rfbport ${VNC_PORT} -rfbauth /.vnc/passwd -display ${DISPLAY} 2>&1 | info
