#!/bin/bash

#BUILD_VCS_REF
#BUILD_VERSION
#BUILD_PROJECT_URL
#BUILD_COMMITER_NAME
#BUILD_COMMITER_MAIL


docker build \
  --build-arg BUILD_VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg BUILD_VERSION=`git rev-parse --abbrev-ref HEAD` \
  --build-arg BUILD_COMMITER_NAME="`git log -1 --pretty=format:'%an'`" \
  --build-arg BUILD_COMMITER_MAIL="`git log -1 --pretty=format:'%ae'`" \
  --build-arg BUILD_PROJECT_URL='https://github.com/mgvazquez/ibgateway' \
  -t $IMAGE_NAME .
